/**
 * Event Story Translation Loader
 * Loads per-event translation files from https://translation.exmeaning.com/translation/eventStory/
 * 
 * Translation files are generated by the server-side translate.py script
 * and contain locale-targeted translations for each episode's TalkData.
 */

import { getTranslationAssetBaseUrl } from "./translations";
import type { UiLocale } from "./i18n";
export interface IEpisodeTranslation {
    scenarioId: string;
    title?: string;
    talkData: Record<string, string>;
}

export interface IEventStoryTranslation {
    meta?: {
        source: 'official_cn' | 'llm' | 'human';
        version: string;
        last_updated: number;
    };
    episodes: Record<string, IEpisodeTranslation>;
}

const EVENT_TRANSLATION_CACHE_LIMIT = 64;
const EVENT_TRANSLATION_CACHE_TTL = 60 * 1000;

interface CachedEventStoryTranslation {
    data: IEventStoryTranslation;
    cachedAt: number;
    revision: string;
}

// Map: locale:eventId -> translation data
const translationCache = new Map<string, CachedEventStoryTranslation>();

// Track in-flight requests to prevent duplicate fetches
const inflightRequests = new Map<string, Promise<IEventStoryTranslation | null>>();

function eventTranslationTarget(locale: UiLocale): "zh-CN" | "en-US" | null {
    if (locale === "zh-CN" || locale === "en-US") return locale;
    return null;
}

export function selectEventStoryLocalizedText(
    locale: UiLocale,
    sourceText?: string,
    zhCNText?: string,
    targetText?: string,
): string {
    if (locale === "zh-CN") return zhCNText || targetText || sourceText || "";
    if (locale === "en-US") return targetText || sourceText || "";
    return sourceText || "";
}

function eventCacheKey(eventId: number, locale: "zh-CN" | "en-US"): string {
    return `${locale}:${eventId}`;
}

function eventTranslationRevision(data: IEventStoryTranslation): string {
    return `${data.meta?.version ?? "legacy"}:${data.meta?.last_updated ?? 0}`;
}

function setEventCache(key: string, data: IEventStoryTranslation): void {
    translationCache.delete(key);
    translationCache.set(key, {
        data,
        cachedAt: Date.now(),
        revision: eventTranslationRevision(data),
    });
    while (translationCache.size > EVENT_TRANSLATION_CACHE_LIMIT) {
        const oldest = translationCache.keys().next().value as string | undefined;
        if (!oldest) break;
        translationCache.delete(oldest);
    }
}

/**
 * Load event story translation for a specific event
 * Returns cached data if available, otherwise fetches from server
 * 
 * @param eventId - The event ID
 * @returns Translation data or null if not available
 */
export async function loadEventStoryTranslation(eventId: number, locale: UiLocale = "zh-CN"): Promise<IEventStoryTranslation | null> {
    const targetLocale = eventTranslationTarget(locale);
    if (!targetLocale) return null;
    const cacheKey = eventCacheKey(eventId, targetLocale);

    const cached = translationCache.get(cacheKey);
    if (cached && Date.now() - cached.cachedAt < EVENT_TRANSLATION_CACHE_TTL) {
        translationCache.delete(cacheKey);
        translationCache.set(cacheKey, cached);
        return cached.data;
    }

    // If already loading, wait for that promise
    if (inflightRequests.has(cacheKey)) {
        return inflightRequests.get(cacheKey)!;
    }

    // Start loading
    const loadPromise = (async (): Promise<IEventStoryTranslation | null> => {
        try {
            const localeBase = getTranslationAssetBaseUrl(targetLocale);
            const response = await fetch(`${localeBase}/eventStory/event_${eventId}.json`, { cache: "no-store" });
            if (!response.ok) {
                // Translation file doesn't exist for this event
                // Don't cache — file may be added later
                return null;
            }
            const data = await response.json();

            // Backward compatibility: check if data has "episodes" key
            let parsedData: IEventStoryTranslation;
            if (data.episodes) {
                parsedData = data as IEventStoryTranslation;
            } else {
                // Treat as old format (just episodes map)
                // Assume it's official_cn since that was the only source using this loader before
                parsedData = {
                    meta: { source: 'official_cn', version: '0.0', last_updated: 0 },
                    episodes: data as Record<string, IEpisodeTranslation>
                };
            }

            // Only cache if data has episodes (not empty/incomplete)
            if (Object.keys(parsedData.episodes).length > 0) {
                if (cached && cached.revision !== eventTranslationRevision(parsedData)) {
                    translationCache.delete(cacheKey);
                }
                setEventCache(cacheKey, parsedData);
            }
            return parsedData;
        } catch (error) {
            console.debug(`Event story translation not found for event ${eventId}:`, error);
            // Don't cache failures — allow retry on next visit
            return null;
        } finally {
            inflightRequests.delete(cacheKey);
        }
    })();

    inflightRequests.set(cacheKey, loadPromise);
    return loadPromise;
}

/**
 * Get translation for a specific text
 * 
 * @param translation - The event story translation data
 * @param episodeNo - The episode number
 * @returns The selected episode translation or null if not found
 */
export function getStoryTranslation(
    translation: IEventStoryTranslation | null,
    episodeNo: number
): IEpisodeTranslation | null {
    if (!translation) return null;
    return translation.episodes[episodeNo.toString()] || null;
}

/**
 * Clear the translation cache (useful for testing or forced refresh)
 */
export function clearEventStoryTranslationCache(locale?: UiLocale): void {
    const targetLocale = locale ? eventTranslationTarget(locale) : null;
    if (locale && !targetLocale) return;
    if (!targetLocale) {
        translationCache.clear();
        inflightRequests.clear();
        return;
    }
    const prefix = `${targetLocale}:`;
    for (const key of translationCache.keys()) {
        if (key.startsWith(prefix)) translationCache.delete(key);
    }
    for (const key of inflightRequests.keys()) {
        if (key.startsWith(prefix)) inflightRequests.delete(key);
    }
}
